'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Users
    Public Property Id As String
    Public Property Email As String
    Public Property EmailConfirmed As Boolean
    Public Property PasswordHash As String
    Public Property SecurityStamp As String
    Public Property PhoneNumber As String
    Public Property PhoneNumberConfirmed As Boolean
    Public Property TwoFactorEnabled As Boolean
    Public Property LockoutEndDateUtc As Nullable(Of Date)
    Public Property LockoutEnabled As Boolean
    Public Property AccessFailedCount As Integer
    Public Property UserName As String
    Public Property FirsName As String
    Public Property LastName As String
    Public Property Locked As Boolean
    Public Property Disabled As Boolean
    Public Property CreationDate As Nullable(Of Date)
    Public Property ModifiedDate As Nullable(Of Date)

    Public Overridable Property UserClaims As ICollection(Of UserClaims) = New HashSet(Of UserClaims)
    Public Overridable Property UserLogins As ICollection(Of UserLogins) = New HashSet(Of UserLogins)
    Public Overridable Property Roles As ICollection(Of Roles) = New HashSet(Of Roles)

End Class
