'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class UserModuleBDEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=UserModuleBDEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Roles() As DbSet(Of Roles)
    Public Overridable Property UserClaims() As DbSet(Of UserClaims)
    Public Overridable Property UserLogins() As DbSet(Of UserLogins)
    Public Overridable Property Users() As DbSet(Of Users)

End Class
