//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioTK.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_Seguridad_PWrecovery
    {
        [Key]
        public System.Guid pw_recovery_uid { get; set; }
        public System.DateTime pw_fecha { get; set; }
        public string pw_codigo { get; set; }
        public System.Guid pw_usuario_uid { get; set; }
        public short pw_usuario_tipo { get; set; }
    
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
