//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioTK.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_BiblioTK_Catalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BiblioTK_Catalogo()
        {
            this.tbl_BiblioTK_Catalogo_Autores = new HashSet<tbl_BiblioTK_Catalogo_Autores>();
            this.tbl_BiblioTK_Catalogo_Temas = new HashSet<tbl_BiblioTK_Catalogo_Temas>();
            this.tbl_BiblioTK_Log = new HashSet<tbl_BiblioTK_Log>();
            this.tbl_BiblioTK_Votacion = new HashSet<tbl_BiblioTK_Votacion>();
        }
        [Key]
        public System.Guid catalogo_uid { get; set; }
        public string class1_id { get; set; }
        public string class2_id { get; set; }
        public string class3_id { get; set; }
        public string class4_id { get; set; }
        public string cat_Class_LCC { get; set; }
        public string cat_Class_Decimal { get; set; }
        public string cat_Titulo { get; set; }
        public string cat_SubTitulo { get; set; }
        public string idioma_id { get; set; }
        public string cat_Edicion { get; set; }
        public string cat_Año { get; set; }
        public string cat_Pais { get; set; }
        public System.Guid Editorial_uid { get; set; }
        public string cat_Sinopsis { get; set; }
        public Nullable<System.DateTime> cat_Upload_Fecha { get; set; }
        public System.Guid usuario_uid { get; set; }
        public string cat_Upload_Tipo { get; set; }
        public string cat_Upload_Link { get; set; }
        public byte cat_status { get; set; }

        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("catalogo_uid")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BiblioTK_Catalogo_Autores> tbl_BiblioTK_Catalogo_Autores { get; set; }
        public virtual tbl_BiblioTK_class4 tbl_BiblioTK_class4 { get; set; }
        public virtual tbl_BiblioTK_Editoriales tbl_BiblioTK_Editoriales { get; set; }
        public virtual tbl_BiblioTK_Idiomas tbl_BiblioTK_Idiomas { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BiblioTK_Catalogo_Temas> tbl_BiblioTK_Catalogo_Temas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BiblioTK_Log> tbl_BiblioTK_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BiblioTK_Votacion> tbl_BiblioTK_Votacion { get; set; }
    }
}
