//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioTK.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_BiblioTK_Catalogo_Temas
    {
        [Key]
        public System.Guid catalogo_uid { get; set; }
        public System.Guid tema_uid { get; set; }
        public short tema_orden { get; set; }
    
        public virtual tbl_BiblioTK_Temas tbl_BiblioTK_Temas { get; set; }
        public virtual tbl_BiblioTK_Catalogo tbl_BiblioTK_Catalogo { get; set; }
    }
}
