//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioTK.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbl_BiblioTK_Catalogo_Autores
    {
        [Key]
        public System.Guid catalogo_uid { get; set; }
         public System.Guid autor_uid { get; set; }
        public byte autor_tipo { get; set; }
    
        public virtual tbl_BiblioTK_Autores tbl_BiblioTK_Autores { get; set; }
        public virtual tbl_BiblioTK_Catalogo tbl_BiblioTK_Catalogo { get; set; }
    }
}
