//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioTKProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BiblioTK_class2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BiblioTK_class2()
        {
            this.tbl_BiblioTK_class3 = new HashSet<tbl_BiblioTK_class3>();
        }
    
        public string class1_id { get; set; }
        public string class2_id { get; set; }
        public string class2_nombre { get; set; }
    
        public virtual tbl_BiblioTK_class1 tbl_BiblioTK_class1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BiblioTK_class3> tbl_BiblioTK_class3 { get; set; }
    }
}
