//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioTKProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BiblioTK_Votacion
    {
        public System.Guid voto_uid { get; set; }
        public System.Guid usuario_uid { get; set; }
        public System.Guid catalogo_uid { get; set; }
        public byte voto { get; set; }
    
        public virtual tbl_BiblioTK_Catalogo tbl_BiblioTK_Catalogo { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
